### ISSUE TITLE
HomeAssitant Add-On

### ISSUE THREAD

**Issue by dAjaY85** [ThePradox/SolarExportControl#2]
Moin, 
es wäre klasse, diesen Container als HomeAssistant Add-On zu erstellen:

https://developers.home-assistant.io/docs/add-ons/publishing/

**Comment by ThePradox** [comment]
Moin, an sich gute Idee! Vor allem die "Locally build containers" scheinen gut zu passen. Allerdings hab ich keinen Supervisor im bzw. HA OS bei mir im Einsatz. Daher kann ich das momentan nicht testen

**Comment by dAjaY85** [comment]
Ich kann das testen. Hab ja in discord geschrieben, kann Ferne bei Tests in homeassistant unterstützen.

**Comment by dAjaY85** [comment]
Ich kann das testen. Hab ja in discord geschrieben, kann Ferne bei Tests in homeassistant unterstützen.

Konntest du bereits ein ha add-on erzeugen?

**Comment by ThePradox** [comment]
Werde ich mir nächste Woche mal anschauen. Komm für die tests drauf zurück

**Comment by tqma1** [comment]
Hallo!
Würde auch gerne beim testen unterstützen….

**Comment by ThePradox** [comment]
Ich hab mir gestern mal die docs angeschaut.  Das ganze scheint leider nur schwierig kompatibel zu diesem Projekt:
1. Die Addons verwenden eine eigene config welche über das GUI gesteuert werden kann. Die Werte auf dieser Config könnte ich dann transformieren in die eigentlich `config.json`. Machbar, aber sehr aufwändig und mit ständigem Wartungsaufwand verbunden
2. Ich habe keinen unterstützten Weg gefunden den User auf das Volume für `/app/config` zugreifen zu lassen um an die `config.json` und `customize.py` zu kommen. Natürlich ist es technisch möglich (SSH, Portainer etc.).

Der Aufwand (und die theoretische installationskomplexität) steht aber meiner Meinung nach nicht im Verhältnis. Da ist es einfacher das normale Docker Image von diesem Repo im HO-Supervisor einzuhängen.
